### ISSUE TITLE
Rainloop Instructions removed?

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized-docs#104]
Hello Andre, 
I saw that you removed the Rainloop instructions, why did you remove them? I think a lot of people will actually like to use Rainloop :) 

https://github.com/mailcow/mailcow-dockerized-docs/commit/6183ef3a23210ca87172c83584f3fc4edb86aa6a

Best wishes,
Timo

**Comment by Ethereal739** [comment]
Thank you, I was looking for this! I really RainLoop so I don't understand why it's being removed either :|

**Comment by andryyy** [comment]
Use AfterLogics Webmail Lite. Not the copy AfterLogics is NOT fine with being sold.

I don’t support RainLoop, sorry.
