### ISSUE TITLE
Minimum System Resources: Disk -> wrong

### ISSUE THREAD

**Issue by ponchofiesta** [mailcow/mailcow-dockerized-docs#150]
Actually  it says:

Resource | mailcow: dockerized
-- | --
Disk | 5 GiB (without emails)

I just installed Docker and did `docker-compose pull`. I was wondering why the first try ended in "no space left on device". I freed some space and pulled again. Result:
```
# du -sh /var/lib/docker
22G     /var/lib/docker
```

**Comment by andryyy** [comment]
It is not 22 G with overlayfs.

You'd need to tell us about your storage driver. :)

**Comment by ponchofiesta** [comment]
I simply followed the docs. It's Debian 9 x86_64 with xfs filesystem running on a vServer.

**Comment by andryyy** [comment]
The Docker storage driver is what I meant.

**Comment by ponchofiesta** [comment]
Server Version: 18.09.6
Storage Driver: vfs

This was choosen automatically.

**Comment by andryyy** [comment]
Probably because of xfs. Try overlayfs. Don’t know if it will work on xfs though.

**Comment by ponchofiesta** [comment]
According to different sources overlay is not supported by xfs with type=0. And aufs is not available in my kernel anymore. So there seems to be no way to use a better storage driver at the moment.

**Comment by andryyy** [comment]
Sorry, finally changed it in the docs... :)
