### ISSUE TITLE
Network Config at Hetzner Cloud :: for what?

### ISSUE THREAD

**Issue by TomSDEVSN** [mailcow/mailcow-dockerized-docs#219]
Just a question about this: https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/#hetzner-cloud-and-probably-others

For what should this get changed? It's just a `virtual network interface` which only attaches the IPv6 address to the main interface. 
And: it also works without the change

**Comment by andryyy** [comment]
Don't think it is necessary anymore. I don't know why or when it was at all. 

May depend on the template. 

Please ask in the community.

**Comment by MAGICCC** [comment]
I finally found my comment, https://github.com/mailcow/mailcow-dockerized/issues/1737#issuecomment-419397526
