### ISSUE TITLE
syslog under debian

### ISSUE THREAD

**Issue by pgollor** [mailcow/mailcow-dockerized-docs#23]
At `firststeps-syslog.md` file there is a workaround to use the `/etc/default/docker` file.
I think it could be better to use the `/etc/docker/daemon.json` file for the docker options like here: [docker documentation](https://docs.docker.com/engine/reference/commandline/dockerd//#daemon-configuration-file)

I tested this with the following content of `/etc/docker/daemon.json`:
```
{
  "log-driver": "syslog",
  "log-opts": {
    "syslog-address": "udp://127.0.0.1:514"
  }
}
```

So i would like to discuss it here before opening a pull request.

**Comment by andryyy** [comment]
Yes, that's the better way. :-) Can you create that PR?

**Comment by pgollor** [comment]
Yes i will do it, but it could take a few days.
