### ISSUE TITLE
False Configuration Example for Gitea

### ISSUE THREAD

**Issue by can0199** [mailcow/mailcow-dockerized-docs#250]
Hey,

i use gitea via mailcow and had problems cloning repositories via ssh. Now it works with a small change in the configuration I think in the instructions is a small error.

Under step 3 following is written:

 Open mailcow.conf and define the binding you want gitea to use for SSH. Example:
`GITEA_SSH_PORT=127.0.0.1:4000
`
but i think the variable should be:
`GITEA_SSH_PORT=4000`

with this its works propperly for me

**Comment by andryyy** [comment]
Hi,

This just defines the binding on the host, doesn't it? Or am I mistaking something?

André

**Comment by can0199** [comment]
yes its right but i think only the port number is required not the local ip adress

**Comment by andryyy** [comment]
It just binds to 127.0.0.1:4000 then instead of 0.0.0.0:4000 when you leave the IP. :)

**Comment by can0199** [comment]
ahh okay  thank you for your fast response i can only get it running if i write there only the port 

thank you for the nice work :)
