### ISSUE TITLE
SOGo theming docs

### ISSUE THREAD

**Issue by vizion8-dan** [mailcow/mailcow-dockerized-docs#265]
Hi, thanks a lot for bringing SOGo-themeing back!

I don't know if its missing in [documentation](https://mailcow.github.io/mailcow-dockerized-docs/u_e-sogo/) or its just me not understanding it right or my configuration - but theming works for me only if I manually add `SOGoUIxDebugEnabled = YES;` to `data/conf/sogo/sogo.conf`.  (Tested on two different servers).

**Comment by andryyy** [comment]
Check https://www.sogo.nu/files/docs/SOGoDevelopersGuide.html

:)

**Comment by andryyy** [comment]
This should be part of the docs. Do you mind creating a PR?

**Comment by vizion8-dan** [comment]
Sure, I'll create a PR over the weekend.

**Comment by andryyy** [comment]
Thank you!!

------ Originalnachricht ------
Von: "Adriano" ***@***.***>
An: "mailcow/mailcow-dockerized-docs" 
***@***.***>
Cc: "André Peters" ***@***.***>; "State change" 
***@***.***>
Gesendet: 01.04.2021 21:40:53
Betreff: Re: [mailcow/mailcow-dockerized-docs] SOGo theming docs (#265)
