### ISSUE TITLE
Ejabberd ssl docs

### ISSUE THREAD

**Issue by SillieWous** [mailcow/mailcow-dockerized-docs#289]
I'm setting up ejabberd for the first time.

From the XMPP guide I see that there needs to be a new certificate for XMPP. Since I'm not using the build in ACME client, I'll have to add my own certs. From the docs it is not entirely clear to me for what subdomains I have to request a cert.

**Comment by MAGICCC** [comment]
Since we removed XMPP from the mailcow I'll close this issue
