### ISSUE TITLE
[Suggestion] Remove Emojis For A More Professional Style, Capitalization, Blog Filtering

### ISSUE THREAD

**Issue by seniorm0ment** [mailcow/mailcow-dockerized-docs#291]
## Remove Emojis
Suggesting removing the use of Emojis on the sites, blog, and docs to create a more professional seeming service and software. The emojis aren't very professional and come across as a bit amateur/childish. May not seem like a major thing, but it can  be quite offputting to some. First impressions are everything.

## Capitalization
Suggesting using proper capitalization for titles and such.

## Filtered Blog/News/Updates
Suggesting blogpost (News/Updates) filtering based on language, and type of post (security, update, critical, etc.).

It could also be _nice to have_  it show commits or something on the main site, so users can see changes they may want and choose to update instead of needing to visit the Github.

**Comment by MAGICCC** [comment]
Hi,

 
> ## Remove Emojis
> 
> Suggesting removing the use of Emojis on the sites, blog, and docs to create a more professional seeming service and software. The emojis aren't very professional and come across as a bit amateur/childish. May not seem like a major thing, but it can be quite offputting to some. First impressions are everything.

Hm do you mean 🐮 + 🐋 = 💕? That's basicly one of the main things about mailcow along with words with 'moo'. I am sure there's a lot of other FOSS software which use such things way too often.

> ## Capitalization
> 
> Suggesting using proper capitalization for titles and such.

Where? If docs, feel free to create PR to fix this. Please keep in mind that 'mailcow' is always in lowercase and it's 'mailcow: dockerized' with the space after the colon

> ## Filtered Blog/News/Updates
> 
> Suggesting blogpost (News/Updates) filtering based on language, and type of post (security, update, critical, etc.).
> 
> It could also be _nice to have_ it show commits or something on the main site, so users can see changes they may want and choose to update instead of needing to visit the Github.

Devs are writing blogposts on https://mailcow.email/  if necessary e.g. for security concerns or breaking changes or just for some info. But yes maybe it can be improved.
The commit history is linked on https://mailcow.email/ which redirects to GH. Maybe its a nice to have to see the commits also there?

**Comment by seniorm0ment** [comment]
>Hm do you mean 🐮 + 🐋 = 💕 ?
Yes, it is also used after many different text fields around the site, such as in Andre's name on the news/updates, heart emoji after donate box, emojis within news and updates, etc.

>That's basicly one of the main things about mailcow along with words with 'moo'.
I hope it's understood how the emojis and sounds could seem "unprofessional" and seemingly an attempt to be "hip" or "modern". 
I know Mailcow is not a "professional" targeted software, however I think it would appeal to all fields without the emojis/sounds. The Cow with the mail symbol logo/icon is more than sufficient imo.

>Capitalization
I meant on the mailcow.email front page, not the docs. I know this is the docs repo, however this seemingly felt like the most appropriate repo for these suggestions.

>The commit history is linked on https://mailcow.email/ which redirects to GH. Maybe its a nice to have to see the commits also there?
Yes my suggestion was to make them visible directly on the page.

Thank you.
