### ISSUE TITLE
Error 404 on "Show configuration guides for email clients and smartphones"

### ISSUE THREAD

**Issue by vacumet** [mailcow/mailcow-dockerized-docs#363]
Hello
I just noticed that if i click "Show configuration guides for email clients and smartphones" i get error "404 - Not found".

The url is:
https://mailcow.github.io/mailcow-dockerized-docs/client/#host=mailcow.lokalen.org&email=user%40domain.tld&name=User+Name&ui=mailcow.domain.tld&port=443

**Comment by MAGICCC** [comment]
See https://github.com/mailcow/mailcow-dockerized/pull/4458

I am on it to add redirects, needs some testing because of the translation plugin
