### ISSUE TITLE
nginx should also have ipv6 disabled

### ISSUE THREAD

**Issue by alparslanozturk** [mailcow/mailcow-dockerized-docs#425]
my docker deamon completly disable ipv6 so nginx also sould be fixed 

nginx: [emerg] socket() [::]:8081 failed (97: Address family not supported by protocol)
nginx: configuration file /etc/nginx/nginx.conf test failed

```
grep '::' data/conf/nginx/*
data/conf/nginx/dynmaps.conf:  listen [::]:8081;
grep: data/conf/nginx/includes: Is a directory
data/conf/nginx/listen_plain.active:listen [::]:80;
data/conf/nginx/listen_ssl.active:listen [::]:443 ssl http2;

```

this document not mention it;
mailcow-dockerized-docs/docs/post_installation/firststeps-disable_ipv6.en.md

**Comment by alparslanozturk** [comment]
with fork or not now my status like this. 
![image](https://user-images.githubusercontent.com/9527118/173792535-5243c22e-b81e-4986-a4db-6aaefc3ea92a.png)

**Comment by DerLinkman** [comment]
Thats the normal mailcow isn´t it?

That here is the Docs repo not the mailcow Repo itself.

**Comment by DerLinkman** [comment]
Solved with: https://github.com/mailcow/mailcow-dockerized-docs/pull/426
