### ISSUE TITLE
Need to update main Update doc about Docker compose v2 upgrade issues

### ISSUE THREAD

**Issue by JDPerf** [mailcow/mailcow-dockerized-docs#427]
As https://github.com/mailcow/mailcow-dockerized/issues/4618 clearly shows there are issues when updating if still using Docker-compose v1. Maybe the update script will be updated to upgrade Docker compose to v2 for us or at least warn us better.

In the meantime, the [update documentation page](https://mailcow.github.io/mailcow-dockerized-docs/i_u_m/i_u_m_update/) needs to refer to the [manual Docker compose upgrade steps in the installation documentation page](https://mailcow.github.io/mailcow-dockerized-docs/i_u_m/i_u_m_install/#install-docker-compose-v2) before upgrading if they still have Docker-compose v1 installed.

**Comment by DerLinkman** [comment]
Thanks.
Please feel free to do a PR for that.

**Comment by DerLinkman** [comment]
Not needed anymore, since we´ve now implemented a docker-compose Update in the update.sh script.
