### ISSUE TITLE
scanner, printer : add a section how to send an email without authentication on port 25

### ISSUE THREAD

**Issue by yboujraf** [mailcow/mailcow-dockerized-docs#455]
Dear,

Is it possible to add a section to describe : 

- How to authorize an IP address without authentication to send an email through port 25 ?

- How to disable "Need fully-qualified hostname" only for the device because the printer, scanner not allowed to send this information when sending email  ?
`NOQUEUE: reject: RCPT from unknown[192.168.0.227]: 504 5.5.2 <NPIF65E56>: Helo command rejected: need fully-qualified hostname; from=<npif65e56@email.com> to=<scan@email.com> proto=ESMTP helo=<NPIF65E56>`

Best Regards,

**Comment by DerLinkman** [comment]
That is more a type of support question. For help use our telegram group: t.me/mailcow

Will close that here since it is not a issue or improvement so to say.
