### ISSUE TITLE
Can you give an example on how to change $PWD to a custom folder?

### ISSUE THREAD

**Issue by etique57** [mailcow/mailcow-dockerized-docs#48]
Hello,

In the backup page, you give an example on how to change the backup file name (which is rather simple) but not on how to change the backup file path:
"You can change the path by adjusting ${PWD} (which equals to the current directory) to any path you have write-access to."
https://mailcow.github.io/mailcow-dockerized-docs/u_e-backup_restore-maildir/

Could you please explicit this?

Thanks!

**Comment by mkuron** [comment]
Simply replace the string `${PWD}` in that command with anything you like, e.g. `/home/admin`.
