### ISSUE TITLE
Roundcube documentation mentions non-existing property for JavaScript code

### ISSUE THREAD

**Issue by tomudding** [mailcow/mailcow-dockerized-docs#506]
This applies both to the English and German documentation.

https://github.com/mailcow/mailcow-dockerized-docs/blob/0ac711e833c215a24894a7bbc35a088d3110861b/docs/third_party/roundcube/third_party-roundcube.en.md#L232

`btnSize` does not exist with the new Bootstrap 5 CSS. It should just use `btn-xs-half` like the SOGO login button.

**Comment by DerLinkman** [comment]
Fixed in: https://github.com/mailcow/mailcow-dockerized-docs/commit/3485b85918e1c059f9417fa33ca23eac29083237

**Comment by tomudding** [comment]
@DerLinkman My mistake, the `btn-xs-half` should be a class on the element, it is not a variable. Can you change it again?

**Comment by DerLinkman** [comment]
Done
