### ISSUE TITLE
source mailcow.conf before docker-compose up

### ISSUE THREAD

**Issue by jhesketh** [mailcow/mailcow-dockerized-docs#56]
In the install docs[0] there are steps to change mailcow.conf (see step 4) but it is not source'd before docker-compose is called (step 5).

Similar notes should be made elsewhere (eg updating) when administering docker.

[0] https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by mkuron** [comment]
That is not necessary. There is a symlink .env to mailcow.conf, so docker-compose automatically reads all variables from that file. You only need to source it manually if you e.g. want to use the database username and password, as here: https://mailcow.github.io/mailcow-dockerized-docs/debug-attach_service/

**Comment by chriswayg** [comment]
The symlink did not actually work for me. It is not a symlink, but a file:

`$ cat .env`
`mailcow.conf`

I finally found the cause of this, as I was downloading the zipped archive from Github:

`wget https://github.com/mailcow/mailcow-dockerized/archive/master.zip`

assuming, that I would receive the same files. Unexpectedly Github messes with symbolic links when downloading this way. Apparently this is a longstanding bug: https://github.com/archiverjs/node-archiver/issues/158 as Github apparently uses node-archiver.
