### ISSUE TITLE
caldav and carddav srv records

### ISSUE THREAD

**Issue by jhesketh** [mailcow/mailcow-dockerized-docs#57]
For easier DAV configuration we could suggest to set up SRV records. eg:

_carddavs._tcp   IN SRV 10 1 443 mail.example.com.
_carddavs._tcp   IN TXT          "path=/SOGo/dav/"
_caldavs._tcp    IN SRV 10 1 443 mail.example.com.
_caldavs._tcp    IN TXT          "path=/SOGo/dav/"

**Comment by Braintelligence** [comment]
@mkuron I hit this today when trying to follow my own PR here: https://github.com/mailcow/mailcow-dockerized-docs/pull/232

This worked flawlessly without these DNS entries before, but for some reason I had issues connecting today (with errors pointing out these missing records based on some RFC) and it stopped only after I added these entries.
Maybe it was only a temporary hiccup tho...

Should we add them to the docs?
