### ISSUE TITLE
Can not find manual update documentation

### ISSUE THREAD

**Issue by yvan-algoo** [mailcow/mailcow-dockerized-docs#618]
Hi,

On https://docs.mailcow.email/i_u_m/i_u_m_update/, it is written `If you think you made a lot of changes to the mailcow code, you should use the manual update guide below`.

Could you tell me where this manual update is described? I can not find it.

Regards,
Yvan

**Comment by MAGICCC** [comment]
It was a way to manually update mailcow, but it's deprecated. The intended way is to use the update script.
I removed the coresponding line, thanks 
https://github.com/mailcow/mailcow-dockerized-docs/pull/620

**Comment by yvan-algoo** [comment]
Thanks @MAGICCC
