### ISSUE TITLE
Add manualconfiguration settings from SMTP/POP/IMAP

### ISSUE THREAD

**Issue by apintocr** [mailcow/mailcow-dockerized-docs#74]
While it's great to have detailed and automated IMAP/EAS configs for the most popular clients, I believe it can be very useful to also document the manual client settings. For example:

- SMTP Port: 25
- SMT Port with SSL: 465

and so on.

**Comment by apintocr** [comment]
I can submit a PR when I have time.

**Comment by andryyy** [comment]
Done, but don't use 25. :-)

**Comment by apintocr** [comment]
Wow that was fast!
Thank you @andryyy

Also, I never use 25… however some people do.
J
I lie! I have port 25 setup on a very old printer that doesn't support SSL :/

**Comment by mkuron** [comment]
@apintocr: In that case, use 587. That is for authenticated submission of messages. That‘s the same as 465, just without SSL.

25 is exclusively for server-to-server communication. We don’t even support authentication on that port, so if you submit messages to it with a recipient address not on your server, you will just get a "relay access denied" error.
