### ISSUE TITLE
Add docker start in Quick installation

### ISSUE THREAD

**Issue by Caspar78** [mailcow/mailcow-dockerized-docs#75]
Hello,

in the Quik Install part of https://mailcow.github.io/mailcow-dockerized-docs/install/
at Point 1, after 

`chmod +x /usr/local/bin/docker-compose`

Add the following for make it easier for docker newbies.

For example on Centos 7
systemctl enable docker
systemctl start docker

Thanks :)

**Comment by andryyy** [comment]
Thanks, fixed it.
