### ISSUE TITLE
Logging drivers

### ISSUE THREAD

**Issue by svengo** [mailcow/mailcow-dockerized-docs#96]
The docker-compose.yml-snippet from https://mailcow.github.io/mailcow-dockerized-docs/firststeps-logging/#logging-drivers doesn't work:

    ERROR: The Compose file './docker-compose.yml' is invalid because:
    services.unbound-mailcow.logging value Additional properties are not allowed ('log_driver' was unexpected)

The following definition must be added for each service instead:

          logging:
            driver: gelf
            options:
              gelf-address: "udp://localhost:12201"
              tag: "mailcow-logs"

**Comment by andryyy** [comment]
Thanks, should have been fixed a while ago. :)
